import { StyleSheet } from 'react-native';
import { moderateScale, verticalScale } from 'react-native-size-matters';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#262E93',
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#565EB3',
  },
  header: {
    padding: moderateScale(20),
    paddingTop: moderateScale(10),
  },
  welcomeText: {
    fontSize: 26,
    color: 'white',
    fontWeight: 'bold',
  },
  dateText: {
    fontSize: 16,
    color: 'white',
    opacity: 0.8,
    marginTop: verticalScale(5),
  },
  estadoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#262E93',
    marginHorizontal: moderateScale(20),
    marginBottom: verticalScale(20),
    padding: moderateScale(15),
    borderRadius: moderateScale(10),
  },
  estadoIndicador: {
    width: moderateScale(12),
    height: moderateScale(12),
    borderRadius: moderateScale(6),
    marginRight: moderateScale(10),
  },
  estadoTexto: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(20),
    marginBottom: verticalScale(20),
  },
  statCard: {
    backgroundColor: '#262E93',
    padding: moderateScale(15),
    borderRadius: moderateScale(10),
    width: '47%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  statNumber: {
    fontSize: 22,
    color: 'white',
    fontWeight: 'bold',
    marginVertical: verticalScale(5),
  },
  statLabel: {
    fontSize: 12,
    color: 'white',
    opacity: 0.8,
    textAlign: 'center',
  },
  pedidoActivoContainer: {
    marginHorizontal: moderateScale(20),
    marginBottom: verticalScale(20),
  },
  pedidoActivoCard: {
    backgroundColor: '#262E93',
    borderRadius: moderateScale(12),
    padding: moderateScale(20),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  pedidoActivoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(15),
  },
  clienteActivoInfo: {
    flex: 1,
  },
  clienteActivoNombre: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: verticalScale(5),
  },
  calificacionActivo: {
    color: 'white',
    marginLeft: moderateScale(5),
    fontSize: 14,
  },
  estadoPedidoTexto: {
    color: '#FFD700',
    fontSize: 14,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  rutaActivaContainer: {
    marginVertical: verticalScale(15),
  },
  direccionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginVertical: verticalScale(8),
  },
  direccionInfo: {
    marginLeft: moderateScale(12),
    flex: 1,
  },
  direccionLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: verticalScale(2),
  },
  direccionTexto: {
    color: 'white',
    fontSize: 14,
    lineHeight: 18,
  },
  separadorRuta: {
    alignItems: 'center',
    marginVertical: verticalScale(5),
  },
  detallesActivoContainer: {
    marginVertical: verticalScale(15),
    paddingTop: verticalScale(15),
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.2)',
  },
  detalleActivo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: verticalScale(6),
  },
  detalleActivoTexto: {
    color: 'white',
    marginLeft: moderateScale(10),
    fontSize: 14,
    opacity: 0.9,
  },
  pagoTexto: {
    color: '#4CAF50',
    marginLeft: moderateScale(10),
    fontSize: 16,
    fontWeight: 'bold',
  },
  botonesContainer: {
    flexDirection: 'row',
    marginTop: verticalScale(20),
    gap: moderateScale(10),
  },
  cancelarButton: {
    flex: 1,
    backgroundColor: '#F44336',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: verticalScale(12),
    borderRadius: moderateScale(25),
  },
  cancelarButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: moderateScale(6),
  },
  navegarButton: {
    flex: 2,
    backgroundColor: '#FF6B35',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: verticalScale(12),
    borderRadius: moderateScale(25),
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  navegarButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: moderateScale(8),
  },
  pedidosContainer: {
    paddingHorizontal: moderateScale(20),
    paddingBottom: verticalScale(20),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(15),
  },
  sectionTitle: {
    fontSize: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  pedidoCard: {
    backgroundColor: '#262E93',
    padding: moderateScale(15),
    borderRadius: moderateScale(10),
    marginBottom: verticalScale(15),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  pedidoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: verticalScale(10),
  },
  clienteInfo: {
    flex: 1,
  },
  clienteNombre: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
  },
  calificacionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(2),
  },
  calificacion: {
    color: 'white',
    marginLeft: moderateScale(5),
    fontSize: 14,
  },
  urgenteBadge: {
    backgroundColor: '#FF5722',
    paddingHorizontal: moderateScale(8),
    paddingVertical: verticalScale(4),
    borderRadius: moderateScale(12),
  },
  urgenteText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  rutaContainer: {
    marginVertical: verticalScale(10),
  },
  rutaPunto: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: verticalScale(2),
  },
  direccion: {
    color: 'white',
    marginLeft: moderateScale(10),
    flex: 1,
    fontSize: 14,
  },
  detallesContainer: {
    marginVertical: verticalScale(10),
  },
  detalle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: verticalScale(2),
  },
  detalleTexto: {
    color: 'white',
    marginLeft: moderateScale(10),
    fontSize: 14,
    opacity: 0.8,
  },
  pedidoFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: verticalScale(15),
    paddingTop: verticalScale(15),
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.2)',
  },
  precio: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
  },
  aceptarButton: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: moderateScale(20),
    paddingVertical: verticalScale(10),
    borderRadius: moderateScale(20),
  },
  aceptarButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  noPedidosContainer: {
    alignItems: 'center',
    padding: moderateScale(40),
  },
  noPedidosTexto: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: verticalScale(15),
  },
  noPedidosSubtexto: {
    color: 'white',
    opacity: 0.7,
    textAlign: 'center',
    marginTop: verticalScale(5),
  },
  input: {
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    marginBottom: 12,
    color: '#222',
  },
  prioridadButton: {
    flex: 1,
    backgroundColor: '#565EB3',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 4,
  },
});

export default styles;